name: "Check just syntax"
description: "Checks for correct syntax in all .just files in repo"
runs:
  using: "composite"
  steps:
    - name: Install just
      uses: extractions/setup-just@e33e0265a09d6d736e2ee1e0eb685ef1de4669ff # v3
    - name: Check just syntax
      run: |
        find "./" -type f -name "*.just" | while read -r file; do
          echo "Checking syntax: $file"
          just --unstable --fmt --check -f $file || { exit 1; }
        done
      shell: bash
